#!/usr/bin/env python3
"""Reads a linear system of equations and solves it and writes result."""
import argparse
from pathlib import Path
import sys
import numpy as np
import linsolver


_DESCRIPTION = """Solves the linear sytem of equation Ax = b. It requires an input file
"linsolve.in", containing the coefficient matrix A (each line of A should be written into a separate
line) followed by the right-hand-side vectorb b in a single row. The script writes a file
"linsolve.out" containing the solution vector x as row vector or an error message if the solver failed"""

INPUT_FILE_NAME = "linsolve.in"

OUTPUT_FILE_NAME = "linsolve.out"


def main():
    """Main script."""
    args = _parse_arguments()
    workdir = Path(args.directory)
    inputfile = workdir / INPUT_FILE_NAME
    try:
        coeffs, rhs = linsolver.io.read_input(inputfile)
    except IOError:
        print(f"Could not read file '{inputfile}'")
        sys.exit(1)

    try:
        result = linsolver.solvers.solve(coeffs, rhs)
    except np.linalg.LinAlgError:
        result = None

    outputfile = workdir / OUTPUT_FILE_NAME
    try:
        if result is None:
            linsolver.io.write_lindep_error(outputfile)
        else:
            linsolver.io.write_result(outputfile, result)
    except IOError:
        print(f"Could not write file '{outputfile}'")
        sys.exit(1)


def _parse_arguments():
    """Parser the command line arguments and returns Namespace object."""
    parser = argparse.ArgumentParser(description=_DESCRIPTION)
    msg = (
        "Directory, where input file is located and where output should be"
        " written to (default: .)"
    )
    parser.add_argument("-d", "--directory", default=".", help=msg)
    args = parser.parse_args()
    return args


if __name__ == "__main__":
    main()
